syntax = "proto3";

package user;

option go_package="./user;userpb";

service User{
    rpc CreateUser(CreateUserRequest) returns (CreateUserResponse);
    rpc DeleteUser(DeleteUserRequest) returns (DeleteUserResponse);
    rpc GetUsers(GetUsersRequest) returns (GetUserResponse);
}

message CreateUserRequest{
    string email = 1;
    string username = 3;
    string name = 4;
    string uuid = 6;
}

message CreateUserResponse{
    string UUID = 1;
    bool success = 2;
}

message DeleteUserRequest{
    string UUID = 1;
}

message DeleteUserResponse{
    bool success = 1;
}

message GetUsersRequest{
    oneof user_ids{
        UserIDList user_id_list = 1;
        string username = 2; 
    }
    repeated string fields = 3;
    string parameter = 4; // ID or Username
}

message UserIDList {
    repeated string user_ids = 1;
}

message GetUserResponse{
    repeated UserEntity users = 1;
}

message UserEntity{
    optional string id = 1;
    optional string username = 2;
	optional  string name = 3;
    optional string bio = 4;
	optional string avatar_url = 5;
	optional string last_seen = 6;
}
