syntax = "proto3";

package user;

option go_package="./user;userpb";

service User{
    rpc CreateUser(CreateUserRequest) returns (CreateUserResponse);
    rpc DeleteUser(DeleteUserRequest) returns (DeleteUserResponse);
}

message CreateUserRequest{
    string email = 1;
    string password = 2;
    string username = 3;
}

message CreateUserResponse{
    string UUID = 1;
    bool success = 2;
}

message DeleteUserRequest{
    string UUID = 1;
}

message DeleteUserResponse{
    bool success = 1;
}
